import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import 'react-lazy-load-image-component/src/effects/blur.css';
import 'react-loading-skeleton/dist/skeleton.css';
import '@/styles/globals.css';

const inter = Urbanist({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Locali',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={inter.className + ' min-h-screen'}>
        {children}
        {/* <Toaster position='top-right' /> */}
      </body>
    </html>
  );
}
